name: 'Set Deploy Info'
description: 'Generates deployment metadata for documentation preview'

inputs:
  preview_url:
    description: 'GitHub Pages preview URL (from deploy-pages action)'
    required: true
  commit_sha:
    description: 'Full commit SHA'
    required: true

outputs:
  preview_url:
    description: 'GitHub Pages preview URL'
    value: ${{ steps.generate-info.outputs.preview_url }}
  build_timestamp:
    description: 'Build timestamp in UTC'
    value: ${{ steps.generate-info.outputs.build_timestamp }}
  commit_sha_short:
    description: 'Shortened commit SHA (7 characters)'
    value: ${{ steps.generate-info.outputs.commit_sha }}

runs:
  using: 'composite'
  steps:
    - name: Generate deployment info
      id: generate-info
      shell: bash
      run: |
        # Use the preview URL from deploy-pages action
        preview_url="${{ inputs.preview_url }}"
        
        # Remove trailing slash if present for consistency
        preview_url="${preview_url%/}"

        # Get build timestamp in UTC
        build_timestamp=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
        commit_sha="${{ inputs.commit_sha }}"

        echo "preview_url=$preview_url" >> $GITHUB_OUTPUT
        echo "build_timestamp=$build_timestamp" >> $GITHUB_OUTPUT
        echo "commit_sha=${commit_sha:0:7}" >> $GITHUB_OUTPUT

        echo "Preview URL: $preview_url"
        echo "Build timestamp: $build_timestamp"
        echo "Commit: ${commit_sha:0:7}"
